### ISSUE TITLE
literówka w 1.1

### ISSUE THREAD

**Issue by notabigthreat** [efiku/php-kurs#10]
"Bywa to przydatne, gdy dane wyrażenie rzeczywiście jest na tyle zawie, że szybciej zrozumiemy jego ideę po przeczytaniu komentarza."

**Comment by event15** [comment]
Poprawimy, z miłą chęcią.

**Comment by event15** [comment]
Naprawione

**Comment by notabigthreat** [comment]
rzeczywiście
